### ISSUE TITLE
Questions about 3498 error and factor-variable

### ISSUE THREAD

**Issue by KenHok** [JanDitzen/nwxtregress#19]
![image](https://user-images.githubusercontent.com/87791050/218360279-9e7b3be8-df15-4413-827e-ce4e90537b94.png)

**Comment by KenHok** [comment]
My Stata version is 17.0

**Comment by JanDitzen** [comment]
Hi KenHok,
thank you very much for your comments. #1 was a bug and is fixed with version 0.2. At the moment we are not allowing factor variables. Regarding your second question: at the moment we are not allowing for factor variables. We might add this feature in the future.
I hope this answers your questions.
Best,
Jan
